# Generated by Django 5.2.8 on 2025-12-10 15:21

import cryptography_modelFiled
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_transaction', '0002_country_booking_is_self_orderrequest_and_more'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='additional_user_comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='tour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='packages.tour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='user_full_name',
            field=models.CharField(default='SAlom', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='user_phone',
            field=models.CharField(default='raqam', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='card_cvv',
            field=cryptography_modelFiled.EncryptedField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='card_number',
            field=cryptography_modelFiled.EncryptedField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='card_owner',
            field=cryptography_modelFiled.EncryptedField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='card_validity_period',
            field=cryptography_modelFiled.EncryptedField(default='12/12', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasetravelersinformation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_travelers_information', to='booking_transaction.country'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
