# Generated by Django 5.2.8 on 2025-12-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_transaction', '0003_orderrequest_additional_user_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecustomerinformation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchasecustomerinformation',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
