# Generated by Django 5.2.8 on 2025-12-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookingStatus',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
