# Generated by Django 5.2.8 on 2025-12-13 10:01

import cryptography_modelFiled
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_remove_booking_status_remove_booking_tour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', cryptography_modelFiled.EncryptedField(blank=True, max_length=255, null=True)),
                ('card_owner', cryptography_modelFiled.EncryptedField(blank=True, max_length=255, null=True)),
                ('card_validity_period', cryptography_modelFiled.EncryptedField(blank=True, max_length=255, null=True)),
                ('card_cvv', cryptography_modelFiled.EncryptedField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bankcard_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
