# Generated by Django 5.2.8 on 2025-12-13 20:17

import cryptography_modelFiled
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_transaction', '0003_orderrequest_additional_user_comment_and_more'),
        ('userProfile', '0004_userbankcardinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_full_name', cryptography_modelFiled.EncryptedField(max_length=255)),
                ('passport_number', cryptography_modelFiled.EncryptedField(max_length=255)),
                ('birth_date', models.DateField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_info', to='booking_transaction.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
