# Generated by Django 5.2.8 on 2025-12-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_userpassportinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassportinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
